### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by kgoedecke**

### CODE REVIEW

**Comment by kgoedecke** [comment]
@kapekost would appreciate if you could do a quick test with the new deps.

**Comment by kapekost** [comment]
Shall I wait for this to pass to test? Are you on these test fixes?

**Comment by kgoedecke** [comment]
@kapekost Yeah I'll have to check what the issue is, any idea?

**Comment by kapekost** [comment]
Seems like no breaking changes around jest, so it must be something with the mock call itself, 
not much experience around this kind of test / lib

do I get it right, it expects the pop up to show a redirect url for www.google.com and then close? maybe then it needs to see the ?code = xxx ? for it to unmount?
odd if that's the case and it was passing before though :/

**Comment by kgoedecke** [comment]
@kapekost Tests are fixed, good for a test from your side!

**Comment by kapekost** [comment]
Great :) I will get back to this tomorrow morning and I will let you know
Thanks!

**Comment by kapekost** [comment]
works well on my side too !

**Review by kapekost — APPROVED** [review]
works well!

**Comment by kgoedecke** [comment]
@kapekost thanks for checking ;) I'll prepare a release then! 🚀

**Pull request merged**
